title: Kenneth Tiet
description: Kenneth Tiet's Personal Website
baseurl: ""
url: https://kennethtiet.github.io

# theme: cvless

# site settings
taglong: Welcome!
tagshort: Jekyll theme

# author settings
author: 
  name: Kenneth Tiet
  email: tietkenneth@gmail.com
photo: assets/files/profile.jpg
address: Foobar Hall 1.23
phone: +1 626 400 9263

# social media links
social:
  github: kennethtiet
  instagram: kenneth_tiet
  linkedin: kennethtiet

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
